from sr_olthad.agents.backtracker.prompts.exhaustive_effort import (
    PROMPT_REGISTRY as EXHAUSTIVE_EFFORT_CLF_PROMPT_REGISTRY,
    SYS_PROMPT_INSERTION_FIELDS_NEEDED as EXHAUSTIVE_EFFORT_CLF_SYS_PROMPT_INSERTION_FIELDS,
    EFFORT_WAS_EXHAUSTIVE_OPTIONS,
)
from sr_olthad.agents.backtracker.prompts.most_worthwhile_pursuit import (
    PROMPT_REGISTRY as MOST_WORTHWHILE_PURSUIT_CLF_PROMPT_REGISTRY,
    SYS_PROMPT_INSERTION_FIELDS_NEEDED as MOST_WORTHWHILE_PURSUIT_CLF_SYS_PROMPT_INSERTION_FIELDS,
    IS_MOST_WORTHWHILE_OPTIONS,
)
from sr_olthad.agents.backtracker.prompts.partial_success import (
    PROMPT_REGISTRY as PARTIAL_SUCCESS_CLF_PROMPT_REGISTRY,
    SYS_PROMPT_INSERTION_FIELDS_NEEDED as PARTIAL_SUCCESS_CLF_SYS_PROMPT_INSERTION_FIELDS,
    WAS_PARTIAL_SUCCESS_OPTIONS,
)
from sr_olthad.agents.backtracker.prompts.successful_completion import (
    PROMPT_REGISTRY as SUCCESSFUL_COMPLETION_CLF_PROMPT_REGISTRY,
    SYS_PROMPT_INSERTION_FIELDS_NEEDED as SUCCESSFUL_COMPLETION_CLF_SYS_PROMPT_INSERTION_FIELDS,
    WAS_SUCCESSFULLY_COMPLETED_OPTIONS,
)
