from enums import SerializationMethod

STRINGIFY_ENV_STATE_SERIALIZATION_METHOD: SerializationMethod = SerializationMethod.YAML
STRINGIFY_OLTHAD_SERIALIZATION_METHOD: SerializationMethod = SerializationMethod.JSON
